AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Nesting all the stacks

Resources:
  FirstBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/parameterless-bucket-stack-mys3bucket-5qd0jhtoo296/01-parameterless-s3-bucket.yaml

  SecondBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-eu-west-1.amazonaws.com/parameterless-bucket-stack-mys3bucket-5qd0jhtoo296/01-parameterless-s3-bucket.yaml
